import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (coagulationProfileData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Coagulation Profile Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${coagulationProfileData.patientName}`, 10, 30);
  doc.text(`Age: ${coagulationProfileData.age}`, 10, 40);
  doc.text(`Gender: ${coagulationProfileData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(coagulationProfileData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`coagulation-profile-${coagulationProfileData.patientName}.pdf`);
};

// Example usage
const coagulationProfileData = {
  patientName: 'Jane Smith',
  age: 60,
  gender: 'Female',
  results: {
    'Prothrombin Time (PT)': '12.5 seconds',
    'International Normalized Ratio (INR)': '1.1',
    'Partial Thromboplastin Time (PTT)': '32.0 seconds',
    'Platelet Count': '250,000/µL',
    'Fibrinogen': '2.5 g/L',
    'D-Dimer': '500 ng/mL',
    'Thrombin Time': '10.2 seconds',
  },
};

generatePDF(coagulationProfileData);
