import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (crpTestData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('C-Reactive Protein (CRP) Quantitative Test Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${crpTestData.patientName}`, 10, 30);
  doc.text(`Age: ${crpTestData.age}`, 10, 40);
  doc.text(`Gender: ${crpTestData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(crpTestData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`crp-test-${crpTestData.patientName}.pdf`);
};

// Example usage
const crpTestData = {
  patientName: 'John Smith',
  age: 50,
  gender: 'Male',
  results: {
    'C-Reactive Protein (CRP)': '5.0 mg/L',
  },
};

generatePDF(crpTestData);
