import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (kidneyFunctionData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Kidney Function Test Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${kidneyFunctionData.patientName}`, 10, 30);
  doc.text(`Age: ${kidneyFunctionData.age}`, 10, 40);
  doc.text(`Gender: ${kidneyFunctionData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(kidneyFunctionData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`kidney-function-${kidneyFunctionData.patientName}.pdf`);
};

// Example usage
const kidneyFunctionData = {
  patientName: 'Jane Smith',
  age: 55,
  gender: 'Female',
  results: {
    'Blood Urea Nitrogen (BUN)': '15 mg/dL',
    'Creatinine': '0.8 mg/dL',
    'Estimated Glomerular Filtration Rate (eGFR)': '85 mL/min/1.73 m²',
    'Uric Acid': '6.5 mg/dL',
    'Urine Protein': 'Negative',
    'Urine Albumin/Creatinine Ratio': '30 mg/g',
  },
};

generatePDF(kidneyFunctionData);
