import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (lftData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Liver Function Test Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${lftData.patientName}`, 10, 30);
  doc.text(`Age: ${lftData.age}`, 10, 40);
  doc.text(`Gender: ${lftData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(lftData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`lft-${lftData.patientName}.pdf`);
};

// Example usage
const lftData = {
  patientName: 'Jane Doe',
  age: 28,
  gender: 'Female',
  results: {
    'Total Bilirubin': '0.8 mg/dL',
    'Direct Bilirubin': '0.2 mg/dL',
    'Indirect Bilirubin': '0.6 mg/dL',
    'Alkaline Phosphatase': '120 U/L',
    'Alanine Aminotransferase (ALT)': '30 U/L',
    'Aspartate Aminotransferase (AST)': '40 U/L',
    'Gamma-Glutamyl Transferase (GGT)': '35 U/L',
    'Total Proteins': '6.5 g/dL',
    'Albumin': '3.5 g/dL',
    'Globulin': '3.0 g/dL',
    'Albumin-Globulin Ratio': '1.17',
  },
};

generatePDF(lftData);
