import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (lipidProfileData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Lipid Profile Test Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${lipidProfileData.patientName}`, 10, 30);
  doc.text(`Age: ${lipidProfileData.age}`, 10, 40);
  doc.text(`Gender: ${lipidProfileData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(lipidProfileData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`lipid-profile-${lipidProfileData.patientName}.pdf`);
};

// Example usage
const lipidProfileData = {
  patientName: 'John Smith',
  age: 45,
  gender: 'Male',
  results: {
    'Total Cholesterol': '200 mg/dL',
    'LDL Cholesterol': '120 mg/dL',
    'HDL Cholesterol': '60 mg/dL',
    'Triglycerides': '120 mg/dL',
    'Non-HDL Cholesterol': '140 mg/dL',
    'VLDL Cholesterol': '30 mg/dL',
    'Cholesterol/HDL Ratio': '3.33',
    'LDL/HDL Ratio': '2.00',
  },
};

generatePDF(lipidProfileData);
