import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (serumElectrolytesData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Serum Electrolytes Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${serumElectrolytesData.patientName}`, 10, 30);
  doc.text(`Age: ${serumElectrolytesData.age}`, 10, 40);
  doc.text(`Gender: ${serumElectrolytesData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(serumElectrolytesData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Electrolyte', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`serum-electrolytes-${serumElectrolytesData.patientName}.pdf`);
};

// Example usage
const serumElectrolytesData = {
  patientName: 'John Smith',
  age: 50,
  gender: 'Male',
  results: {
    'Sodium (Na)': '138 mEq/L',
    'Potassium (K)': '4.2 mEq/L',
    'Chloride (Cl)': '102 mEq/L',
    'Bicarbonate (HCO3)': '24 mEq/L',
    'Calcium (Ca)': '9.2 mg/dL',
    'Magnesium (Mg)': '1.8 mg/dL',
    'Phosphorus (P)': '3.2 mg/dL',
  },
};

generatePDF(serumElectrolytesData);
