import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (thyroidProfileData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Thyroid Profile 2 Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${thyroidProfileData.patientName}`, 10, 30);
  doc.text(`Age: ${thyroidProfileData.age}`, 10, 40);
  doc.text(`Gender: ${thyroidProfileData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(thyroidProfileData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Test', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`thyroid-profile-2-${thyroidProfileData.patientName}.pdf`);
};

// Example usage
const thyroidProfileData = {
  patientName: 'Jane Doe',
  age: 40,
  gender: 'Female',
  results: {
    'Thyroid-Stimulating Hormone (TSH)': '0.5 mIU/L',
    'Free Thyroxine (T4)': '1.8 ng/dL',
    'Free Triiodothyronine (T3)': '3.2 pg/mL',
    'Thyroglobulin (Tg)': '10 ng/mL',
    'Thyroid-Stimulating Immunoglobulin (TSI)': '0.5 IU/mL',
  },
};

generatePDF(thyroidProfileData);
