import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (widalTestData) => {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.text('Widal Test Report', 10, 10);

  // Add patient details
  doc.setFontSize(12);
  doc.text(`Patient Name: ${widalTestData.patientName}`, 10, 30);
  doc.text(`Age: ${widalTestData.age}`, 10, 40);
  doc.text(`Gender: ${widalTestData.gender}`, 10, 50);

  // Add table
  const tableData = Object.entries(widalTestData.results).map(([key, value]) => [key, value]);
  const tableHeaders = [['Antigen', 'Result']];
  const tableBody = [...tableHeaders, ...tableData];

  doc.autoTable({
    head: tableHeaders,
    body: tableBody,
    startY: 60,
    styles: {
      fontSize: 12,
      cellPadding: 2,
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
      overflow: 'linebreak',
      halign: 'left',
      valign: 'middle',
      fontStyle: 'normal',
    },
    headStyles: {
      fillColor: [100, 400, 200],
      textColor: [0, 70, 0],
      fontStyle: 'bold',
    },
  });

  // Add footer
  const footerText = 'Generated by Your Clinic Name';
  const footerY = doc.internal.pageSize.height - 20;
  const footerX = doc.internal.pageSize.width / 2;
  doc.setFontSize(10);
  doc.text(footerText, footerX, footerY, { align: 'center' });

  doc.save(`widal-test-${widalTestData.patientName}.pdf`);
};

// Example usage
const widalTestData = {
  patientName: 'John Smith',
  age: 40,
  gender: 'Male',
  results: {
    'Salmonella Typhi O Antigen': 'Negative',
    'Salmonella Typhi H Antigen': 'Negative',
    'Salmonella Paratyphi A Antigen': 'Negative',
    'Salmonella Paratyphi B Antigen': 'Negative',
  },
};

generatePDF(widalTestData);
